# Generated by Django 4.2.4 on 2023-08-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='albom',
        ),
        migrations.AddField(
            model_name='albom',
            name='song',
            field=models.ManyToManyField(to='music.song', verbose_name='Песня'),
        ),
    ]
