# Generated by Django 4.2.4 on 2023-08-22 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_albom_albom_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='serial_number',
        ),
    ]
