# Generated by Django 4.2.4 on 2023-08-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_song_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ManyToManyField(to='music.singer', verbose_name='Исполнитель'),
        ),
    ]
